title = "Occasional Divergences"
baseURL = "https://www.occasionaldivergences.com/"
theme = "hyde"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
paginate = 10
enableEmoji = true

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[params]
  description = "A website built through Hugo and blogdown."
  EnableEmoji = true
  layoutReverse = true
  themeColor = "theme-base-08"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"
