---
title: "Modeling workflow with tidymodels"
author: "Marc Dotson"
date: "2020-11-30"
slug: tidy-models
---

Intro.

## Model building

- Define the model conceptually
- Consider the data generating process (including model type)
- Perform prior predictive checks
- Data splitting (test/train)
- Data wrangling/pre-processing?

## Model fitting

- Set the engine, including setting priors
- Run the model and check diagnostics

## Model validation

- Tidy output
- Perform posterior predictive checks
- Model fit and prediction

-----

### Marc Dotson

Marc is an assistant professor of marketing at the BYU Marriott School of Business. He graduated with an MSc from The London School of Economics and Political Science in 2009 and a PhD from The Ohio State University in 2016. His research interests include Bayesian inference, predictive modeling, consumer preference heterogeneity, and unstructured data. Marc teaches marketing analytics. You can find him on [Twitter](https://twitter.com/marcdotson) and [GitHub](https://github.com/marcdotson).
